### ISSUE TITLE
Proxy / X-Forwarded-For support

### ISSUE THREAD

**Issue by markstos** [wmhilton/whitelist-ips#2]
Are proxies support or the X-Forward-For header?

When a request comes through a proxy, the req.ip will belong to the proxy and the originating IP will be in the X-Forwarded-For header.

From reading the code and docs, I don't see any mention of this.

It would be possible to chain this with another middleware that makes sure that req.ip is set to the original IP and not a proxy before this middleware runs. If that's the recommended approach, it would be helpful to document it.

**Comment by billiegoose** [comment]
The X-Forwarded-For header is easy to spoof... If you're using a proxy server I think the simpler solution is just to add the IP of your proxy server to the whitelist.

Although I can't remember why I created this module, so I don't remember if it was for security or to prevent hotlinking images...

Oh, oh, hang on I see what you're talking about. Yes, I designed the module _specifically_ for the use case of proxies in mind - I wanted to make sure the server only accepted requests (to certain routes/URLs) that came through the load-balancing server (e.g. CloudFlare) so that clever people couldn't overwhelm the server with a DOS attack. I never intended it to be used to whitelist *user* IP addresses, which is what would be stored in the X-Forwarded-For header. Does that make sense?

**Comment by markstos** [comment]
I found that that the [req-ip](https://github.com/bendrucker/req-ip) module can be used first in a middleware chain to achieve the result I want.

In the case of stopping a DOS account, you would minimize the impact by stopping the attack as close to the edge of your network as you can. If that's the concern, I would consider whitelisting IPs with an OS firewall or an Nginx reverse proxy  before I would implement it in Express. 

If the attacker can get as far as getting your JavaScript engine to spend any CPU on a response-- even just to reject the response-- they are already in a position to do more damage. If the OS just dropped the connection, you'd be able to withstand larger attacks.

**Comment by billiegoose** [comment]
True! I guess an OS-level firewall would have made the most sense for that use case. I think I was mostly worried about exceeding my bandwidth limits... IIRC had a large static images directory that I was trying to protect by using Cloudflare's CDN to cache images. But it was 3 years ago, and I was running a startup on a shoestring budget and doing too many things.

Feel free to open a PR adding a section to the README documenting how you did what you did! Somebody might find it useful.
